### ISSUE TITLE
Handling Problem 2

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project6#4]
As a team developer, I want to convert the Photo App to use Axios instead of our custom FetchModel routine for fetching data from the web server, so that we can prepare for the upcoming assignment involving more extensive use of the REST API. Axios is a powerful npm package that offers faster data fetching and increased functionality compared to our existing FetchModel function. By making this transition, we ensure that our app remains fully functional while also benefiting from the capabilities of Axios.

Acceptance Criteria:

      1. Migrate to Axios for data fetching, replacing FetchModel.
      2. Replace all FetchModel calls with Axios equivalents.
      3. Implement error handling using .catch with Axios for requests.
      4. Ensure consistent logic in handlers with minimal changes.
      5. Update documentation to reflect Axios usage and provide references.
      6. Thoroughly test the app to maintain identical functionality before and after migration.

By completing this migration to Axios, we aim to prepare the Photo App for the next assignment while enhancing its data fetching capabilities. We ensure that the app remains fully functional and that the transition does not introduce any unintended issues or changes in functionality.

**Comment by KASHO7** [comment]
Axios has been implemented successfully

**Comment by aalqah13** [comment]
Thank you for the feedback.
